name: Unit tests

on:
  pull_request:
    branches:
        - develop

jobs:
  Unit_tests:
    name: Unit tests
    runs-on: macos-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: setup-cocoapods
            uses: maxim-lobanov/setup-cocoapods@v1.1
            with:
                podfile-path: myApp/Podfile.lock
        - name: Run tests
          run: xcodebuild -workspace KarumiTest.workspace
            -scheme KarumiTestTests
            -destination platform=iOS\ Simulator,OS=13.5,name=iPhone\ 11
            test | xcpretty
