name: Unit tests

on:
  pull_request:
    branches:
        - develop

jobs:
  Unit_tests:
    name: Unit tests
    runs-on: macos-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: pod install --repo-update
        - name: Run tests
          run: xcodebuild -workspace KarumiTest.xcworkspace
            -scheme KarumiTestTests
            -destination platform=iOS\ Simulator,OS=13.5,name=iPhone\ 11
            test | xcpretty
        - name: Code coverage
          uses: codecov/codecov-action@v1
          with:
            token: e728ca9d-8b07-4cd1-85c4-cf3f2e7beff1
